-- Follow-up to 012: drinks and soups from the CSV import are per 100 ml,
-- not 100 g. Relabel them so the unit toggle shows "ml" for liquids.
-- Explicit hand-reviewed name list — solids that merely mention a liquid
-- (e.g. "Coffee biscuit", "Milk cake", "Rasam powder") are deliberately
-- NOT included.

update foods
set serving = '100 ml'
where source = 'seed'
  and name in (
    'Almond soup (Badam ka soup)',
    'Apple oats chia seed smoothie',
    'Baked potato soup',
    'Banana milkshake (Kele milkshake)',
    'Banana milkshake with ice cream (Kele ka milkshake ice cream ke saath)',
    'Bottle gourd soup (Ghiya/Lauki soup)',
    'Cheese soup',
    'Chicken consomme (Clear chicken soup)',
    'Chicken sweet corn soup',
    'Chinese cabbage and meat ball soup',
    'Clear tomato soup (Tamatar ka soup)',
    'Coco pine cooler',
    'Cold coffee (with cream)',
    'Cold coffee with ice cream',
    'Cold cucumber cream soup',
    'Cold cucumber soup (Thanda kheere ka soup)',
    'Cold summer garden soup',
    'Cold tomato soup',
    'Cream of broccoli soup',
    'Cream of carrot soup',
    'Cream of green peas soup',
    'Cream of mixed vegetable soup',
    'Cream of mushroom soup',
    'Cream of potato soup',
    'Cream of spinach soup',
    'Cream of tomato soup',
    'Cucumber sharbat (Kheere ka sharbat)',
    'Cumin infused water (Jeere/Zeere ka pani)',
    'Curried Cauliflower soup',
    'Egg drop soup',
    'Espreso coffee',
    'Flavoured milkshake',
    'French onion soup',
    'Fruit Punch (with fresh juices)',
    'Fruit Punch (with squashes)',
    'Garlic chickpea soup (Lahasun aur chane ka shoraba)',
    'Garlic soup',
    'Green pea soup (Matar ka soup)',
    'Ham and Bean soup',
    'Hot and sour soup',
    'Hot cocoa',
    'Hot tea (Garam Chai)',
    'Iced tea',
    'Instant coffee',
    'Kashmiri tea (Kehwa)',
    'Lassi (salted)',
    'Lem-o-gin',
    'Lemon and ginger squash (Nimbu aur adrak ka squash)',
    'Lemon coriander soup',
    'Lemon squash (Nimbu ka squash)',
    'Lemonade',
    'Lentil soup',
    'Lichi squash',
    'Mango milkshake (Aam milkshake)',
    'Mango milkshake with ice cream (Aam milkshake ice cream ke saath)',
    'Mango squash (Aam ka squash)',
    'Millet soup',
    'Minestrone soup',
    'Mixed vegetable soup',
    'Mulligatawny soup',
    'Nannari sharbat',
    'Orange milkshake (Narangi milkshake)',
    'Orange milkshake with ice cream (Narangi milkshake ice cream ke saath)',
    'Orange squash (Santre ka squash)',
    'Paneer soup',
    'Pineapple milkshake (Ananas milkshake)',
    'Pineapple milkshake with ice cream (Ananas milkshake ice cream ke saath)',
    'Pineapple squash (Ananas ka squash)',
    'Plum squash (Aloo bukhara squash)',
    'Pumpkin soup',
    'Rasam with lemon (Nimmakaya rasam/Nimmakaya charu/Elumichai rasam/Nimbe hannina saaru)',
    'Rasam with tamarind (Puli rasam/ Chintapandu rasam/ Charu/Saaru)',
    'Raw mango drink (Aam panna)',
    'Saffron milk (Kesariya doodh)',
    'Sattu drink',
    'Semolina milk drink (Thari kanji)',
    'Spinach soup (Palak ka soup)',
    'Spinach soup in milk',
    'Steeped hot coffee',
    'Summer cooler',
    'Sweet Lassi (Meethi lassi)',
    'Sweet corn soup',
    'Talaumein soup',
    'Thandai',
    'Vegetable soup',
    'Whey soup',
    'Woodapple juice (Bel ka sharbat)'
  );
